# Generated by Django 4.0.3 on 2022-03-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('mapYLocation', models.IntegerField()),
                ('mapXLocation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('setter', models.CharField(max_length=20)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClimbingGymTrainer.area')),
            ],
        ),
    ]
