# Generated by Django 4.0.3 on 2022-03-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymTrainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='value',
        ),
    ]
